language: node_js

os:
  - linux
  - windows

node_js:
  - "8.9.0"
  - "lts/*"

matrix:
  include:
    - os: linux
      env: COVERAGE=1
    - os: windows
      env: EXCLUDE_ASSETS=1

script:
  - npm test -- ${COVERAGE:+--coverage --collectCoverageFrom='src/**/*.js' --coverageReporters=lcov} ${EXCLUDE_ASSETS:+--testPathIgnorePatterns assets.test.js}
  - if [ -f "test/.coverage/lcov.info" ]; then cat test/.coverage/lcov.info | coveralls ; fi
