language: node_js

jobs:
  include:
    - os: linux
      node_js: "8.9.0"
    - os: linux
      node_js: "lts/*"
    - os: windows
      node_js: "8.9.0"
      env: EXCLUDE_ASSETS=1
    - os: windows
      node_js: "lts/*"
      env: EXCLUDE_ASSETS=1

script:
  - npm test -- --coverage ${EXCLUDE_ASSETS:+--testPathIgnorePatterns assets.test.js}

after_success:
  - cat test/.coverage/lcov.info | coveralls
