language: node_js

os:
  - linux
  - windows

node_js:
  - "8.9.0"
  - "lts/*"

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm test -- --coverage --collectCoverageFrom='src/**/*.js' --coverageReporters=lcov ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm test -- --testPathIgnorePatterns assets.test.js ; fi
  - if [ -f "test/.coverage/lcov.info" ]; then cat test/.coverage/lcov.info | coveralls ; fi
