language: node_js

os:
  - linux
  - windows

node_js:
  - "8.9.0"
  - "lts/*"

script:
  - npm test -- --coverage --collectCoverageFrom='src/**/*.js' --coverageReporters=text-lcov
  - cat test/.coverage/lcov.info | coveralls
