language: node_js

os:
  - linux
  - windows

node_js:
  - "8.9.0"
  - "lts/*"

env:
  # We need to preserve builds for linux without env
  - PRESERVE_BUILD=LINUX
  - EXCLUDE_ASSETS=1

jobs:
  exclude:
    - os: linux
      env: EXCLUDE_ASSETS=1
    - os: windows
      env: PRESERVE_BUILD=LINUX

script:
  - npm test -- --coverage ${EXCLUDE_ASSETS:+--testPathIgnorePatterns assets.test.js}

after_success:
  - cat test/.coverage/lcov.info | coveralls
