language: node_js

os:
  - linux
  - windows

node_js:
  - "8.9.0"
  - "lts/*"

env:
  - EXCLUDE_ASSETS=1

jobs:
  exclude:
    - os: linux
      env: EXCLUDE_ASSETS=1

script:
  - npm test -- --coverage ${EXCLUDE_ASSETS:+--testPathIgnorePatterns assets.test.js}

after_success:
  - cat test/.coverage/lcov.info | coveralls
